name: jupyter-flex
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - pip:
    # Package dev
    - notebook
    - jupyterlab
    - nbconvert
    - voila
    - ipywidgets
    - jupyter-flex
    - versioneer
    - twine
    - pytest
    - pytest-base-url
    - pytest-html
    - pytest-selenium
    - pytest-needle
    # Docs
    - mkdocs
    - mkdocs-material
    - mkdocs-jupyter
    - mkdocs-minify-plugin
    - libsass
    - pygments
    - pymdown-extensions
    # Used by examples
    - altair
    - plotly
    - bqplot
    - bokeh
    - jupyter_bokeh
    - qgrid
    - pandas-datareader
    - colorlover
    - vega_datasets
