name: jupyter-flex
channels:
  - conda-forge
dependencies:
  - python=3
  - pip
  - notebook
  - jupyterlab
  - ipython
  - voila
  - nbconvert
  - ipywidgets
  - libsass
  - mkdocs
  - pygments
  # Used by examples
  - pandas
  - matplotlib
  - plotly
  - bokeh
  - bqplot
  - pandas-datareader
  - scikit-learn
  - pip:
    - versioneer
    - twine
    - mkdocs-material
    - mkdocs-jupyter
    - pymdown-extensions
    - jupyter_bokeh
    - colorlover
