site_name: Jupyter-flex
site_url: https://github.com/danielfrg/jupyter-flex
copyright: Daniel Rodriguez

nav:
- Home: index.md
- Getting Started: getting-started.ipynb
- Layout: layout.md

theme:
  name: 'material'
  custom_dir: 'docs/theme'
  favicon: 'assets/img/favicon.ico'
  palette:
    primary: 'orange'
    accent: 'red'
  logo:
    icon: 'dashboard'

extra_css:
  - assets/css/custom.css

extra_javascript:
  - 'assets/js/require.min.js'

repo_name: 'danielfrg/jupyter-flex'
repo_url: 'https://github.com/danielfrg/jupyter-flex'

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - admonition
