site_name: Jupyter-flex
site_url: https://jupyter-flex.danielfrg.com
copyright: Copyright 2019 - 2021 Daniel Rodriguez

nav:
  - Home: index.md
  - Getting started: getting-started.ipynb
  - Layouts: layouts.ipynb
  - Plotting: plotting.ipynb
  - Voila & Widgets: voila-widgets.ipynb
  - Customization: customization.ipynb
  - Reference: reference.md

repo_name: danielfrg/jupyter-flex
repo_url: https://github.com/danielfrg/jupyter-flex
edit_uri: ""

theme:
  name: material
  custom_dir: docs/theme
  favicon: assets/img/favicon.png
  logo: assets/img/icon.png

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

plugins:
  - search
  - mkdocs-jupyter:
      execute: false

markdown_extensions:
  - meta
  - admonition
  - codehilite
  - toc:
      permalink: true

google_analytics:
  - "UA-35523657-5"
  - "auto"
