name: jupyter-flex
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip

  # Dev tools
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel

  - pip:
      # Package deps
      - voila>=0.2.0,<0.3
      - nbconvert>=6.0.0,<7
      - nbclient>=0.4.0
      - jupyter_server>=1.1.0
      - illusionist>=0.2.0

      # Testing
      - pytest
      - pytest-cov
      - pytest-html
      - pytest-needle
      - pytest-base-url
      - pytest-selenium
      - pytest-tornasync

      # Docs
      - mkdocs>=1.1.0,<2
      - mkdocs-material==7.1.0
      - mkdocs-jupyter>=0.16.1
      - mkdocs-minify-plugin
      - pygments
      - pymdown-extensions

      # Examples
      - notebook
      - jupyterlab
      - ipywidgets
      - numpy
      - pandas
      - scipy
      - matplotlib
      - scikit-learn
      - statsmodels
      - altair
      - plotly
      - bqplot
      - bokeh
      - jupyter_bokeh
      - qgrid
      - ipyleaflet
      - ipysheet
      - pandas-datareader
      - colorlover
      - vega_datasets
